name: "CodeQL for Specific Branch"

on:
  push:
    branches: 
      - "Sub-Naveen" # Replace with your specific branch name
  pull_request:
    branches: 
      - "Sub-Naveen" # Replace with your specific branch name
  schedule:
    - cron: '27 11 * * 5' # Optional: Scheduled runs

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: 'javascript-typescript'
            build-mode: 'none' # Use 'none' for JavaScript/TypeScript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the version of Node.js your project requires

      - name: Install dependencies
        run: npm install

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

      - name: Notify on Completion
        if: always()  # Ensure this runs even if previous steps fail
        run: echo "CodeQL analysis completed. Check workflow logs for details."

      - name: Print Security Findings
        if: always()  # Ensure this runs even if previous steps fail
        run: |
          echo "Security findings summary:"
          # Add logic to parse and print security findings summary from logs if needed

      - name: Email Notification
        if: always() && success()  # Send email on successful completion
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: naveen.chinnasamy@ennvee.net
          server_port: 587
          username: "Naveen Chinnasamy"
          password: "Chn442ens"
          subject: "CodeQL Analysis Results"
          body: |
            CodeQL analysis for branch '${{ github.ref }}' completed successfully.
            Review the security findings in the workflow logs.
