jobs:
  php-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP and Composer
        run: |
          sudo apt-get update
          sudo apt-get install php
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --filename=composer --install-dir=/usr/local/bin
          php -r "unlink('composer-setup.php');"

      - name: Verify Composer installation
        run: composer --version

      - name: Run Psalm Security Scan
        run: php ./path/to/composer.phar require psalm/psalm-github-security-scan

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
