name: "CodeQL for Specific Branch"

on:
  push:
    branches: 
      - "Sub-Naveen" # Replace with your specific branch name
  pull_request:
    branches: 
      - "Sub-Naveen" # Replace with your specific branch name

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: 'javascript'
            build-mode: 'none' # Use 'none' for JavaScript
          - language: 'php'
            build-mode: 'none' # PHP does not require a build step

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the version of Node.js your project requires

      - name: Install dependencies for JavaScript
        if: matrix.language == 'javascript'
        run: npm install

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
