name: "CodeQL for Specific Branch"

on:
  push:
    branches: 
      - "Sub-Naveen" # Replace with your specific branch name
  pull_request:
    branches: 
      - "Sub-Naveen" # Replace with your specific branch name
  schedule:
    - cron: '27 11 * * 5' # Optional: Scheduled runs

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: 'javascript-typescript'
            build-mode: 'autobuild' # Use 'autobuild' for automatic builds

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use the version of Node.js your project requires

    - name: Install dependencies
      run: npm install

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - if: matrix.build-mode == 'manual'
      shell: bash
      run: |
        # Provide manual build commands here if needed
        echo 'Building project manually...'
        exit 1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
