name: Psalm Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        run: |
          sudo apt-get update
          sudo apt-get install php-cli php-zip php-dom php-mbstring
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Verify Composer installation
        run: composer --version

      - name: Add Custom Repository
        run: |
          composer config repositories.psalm-github-security-scan vcs https://github.com/psalm/psalm-github-security-scan

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Psalm Security Scan
        run: vendor/bin/psalm --version

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
