name: Psalm Analysis and Security Check

on:
  push:
    branches:
      - Sub-Naveen  # Adjust branch as needed
  pull_request:
    branches:
      - Sub-Naveen  # Adjust branch as needed

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' 

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Psalm
        run: php vendor/bin/psalm --config=psalm.xml --output-format=sarif --report=psalm.sarif
        continue-on-error: true

      - name: Upload Psalm SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: psalm.sarif

      - name: Install PHP Security Checker
        run: composer global require enlightn/security-checker

      - name: Run Security Check and Save JSON Output
        run: ~/.composer/vendor/bin/security-checker security:check --format=json > security.json

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Convert JSON to SARIF
        run: |
          echo '{
            "version": "2.1.0",
            "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "PHP Security Checker",
                    "informationUri": "https://github.com/enlightn/security-checker",
                    "rules": []
                  }
                },
                "results": []
              }
            ]
          }' > security.sarif

          jq -r '. | {
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "PHP Security Checker",
                    "rules": [
                      (.vulnerabilities[] | {
                        "id": .advisoryId,
                        "shortDescription": { "text": .title },
                        "fullDescription": { "text": .link }
                      })
                    ]
                  }
                },
                "results": [
                  (.vulnerabilities[] | {
                    "ruleId": .advisoryId,
                    "message": { "text": .title },
                    "locations": [
                      {
                        "physicalLocation": {
                          "artifactLocation": { "uri": "composer.lock" },
                          "region": {
                            "startLine": 1,
                            "startColumn": 1
                          }
                        }
                      }
                    ]
                  })
                ]
              }
            ]
          }' security.json | jq -s '.[0].runs[0].tool.driver.rules = [.[0].runs[0].tool.driver.rules] | .[0].runs[0].results = [.[0].runs[0].results] | .[0]' >> security.sarif

      - name: Upload Security Checker SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: security.sarif
