name: Psalm Analysis

on:
  push:
    branches:
      - Sub-Naveen  # Adjust branch as needed
  pull_request:
    branches:
      - Sub-Naveen  # Adjust branch as needed

jobs:
  psalm:
    name: Psalm Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' 

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions:5.7.7
        with:
          security_analysis: true
          report_file: results.sarif
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Run Psalm
        run: php vendor/bin/psalm --config=psalm.xml --output-format=sarif --report=psalm.sarif
        continue-on-error: true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: psalm.sarif
